apt update

2. apt upgrade

3. pkg update && pkg upgrade

4. pkg install bash

5. pkg install git

6. pkg install nodejs

7. pkg install ffmpeg

8. pkg install wget

9. pkg install imagemagick

10. pkg install yarn

11. termux-setup-storage

12. cd /sdcard

13. cd / jaha file ectract ki ha os ki location and enter

14. yarn install

15. npm start

agar termux exit ho jata ha to again start karny valy command bh dykh loo 

cd /sdcard      
  
cd / file name loaction or phir os ky bad ya vala command ğŸ‘‰ğŸ» npm start
